### PR TITLE
I1652 peers rest api address

### PR DESCRIPTION
**Pull request by pragmaxim**
See https://github.com/ergoplatform/ergo/issues/1652

I gave a lot of thought into backward compatibility, `PeerSpec` is using hand-written writer/reader and new `restApiUrl` optional field is at the end, with a little hack that allows for reading older `PeerSpec` bytes by newer peer version ... And old peers just won't see the extra `PeerSpec` bytes at the end ... 

I noticed that if anything goes wrong with loading peers from PeerDatabase, the node gets stuck, so I added a fallback to loading peers only from network for better user experience + log ERROR.

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Thank you for the implementation! It looks like what was requested, unfortunately I cannot test the implementation.
What I think should be added somewhere is a documentation to the new configuration entry. Where is such documentation added for now?

Also adding @greenhat to the reviewers as he needs the feature as well.

**Comment by pragmaxim** [comment]
@MrStahlfelge the `application.conf` is documented, I will add it here : 
https://github.com/ergoplatform/ergo/wiki/Set-up-a-full-node#update-config-file-with-api-key-hash

basically you just add `scorex.restApi.publicUrl = "https://example.com"` to the `ergo.conf` if the node exposes it ...

**Comment by greenhat** [comment]
Hey! @pragmaxim thank you for taking care of this! Looks good!
I'm wondering if we could lower the friction for the node operators and allow the hostname to be set to "0.0.0.0" and treat it on the clients as "use the same IP as `address` field in peers/connected". It should make life easier for the node operators that have dynamic white IPs. On the second thought that might add more confusion, so it might not be a good idea after all.

**Comment by MrStahlfelge** [comment]
Problem here would be the port, but the node should know the port it uses and could fill it in correctly.

**Comment by pragmaxim** [comment]
I leave this up to you guys, I haven't done any client apps talking to node yet ... If we should just switch the port on the node's address, then the config would be something like `publicRestApiEnabled = true` ... But @MrStahlfelge mentioned some concerns with wifis and firewalls ... ?

**Comment by MrStahlfelge** [comment]
http://....:9053 is blocked on many company networks or public wifis, people regularly contact me about it. So a hostname url with https support is fortunate to have and should be able to be reported by the api.

**Comment by pragmaxim** [comment]
@MrStahlfelge @greenhat My thinking also was that this address should be probably a domain name or static IP address as it is called by a user-facing application and therefor it should be reliably accessible ... whereas the addresses from binding to `0.0.0.0` are often dynamic and not persistent in time. This problem resolves in peer-to-peer network automatically by simply discarding unreachable peers...  

Also the unstable and unreliable peers that could be up/down should not get listed perhaps either as it would be another source of unreliability ...

**Comment by MrStahlfelge** [comment]
@pragmaxim Was this a question, a con or a pro for leaving it as it is? I agree on everything you've wrote but I am not sure what conclusion you take from it.

**Comment by pragmaxim** [comment]
@MrStahlfelge Question is how many node operators is going to be there with a DNS record ... if at least 3 such nodes are going to be there, I'd incline to the current version as this settings basically says "hey, everyone can use this node" ... There could be node operators who want the restAPI to be exposed but just for their own use, they would not use this setting at all.

**Comment by MrStahlfelge** [comment]
If they don't want the rest api to be exposed, they should not set it as exposed in the settings - that is exactly what my request was aiming for.

**Review by kushti — APPROVED** [review]

**Pull request merged**
