### PR TITLE
i1633 Set log level in conf

### LINKED ISSUE #1633: Set Loglevel via ergo.conf
At the moment, the ERGO daemon produces a lot of info messages to stdout, at least when run in docker. It is impossible to control the loglevel via the daemon configuration, only via java options. Please add the possibility to control the log level with the daemon configuration file.

### PR DESCRIPTION
**Pull request by ross-weir**
closes #1633

### CODE REVIEW

**Review by pragmaxim — APPROVED** [review]

**Review by kushti — APPROVED** [review]

**Review by kushti — APPROVED** [review]

**Comment by pragmaxim** [comment]
@ross-weir I tried to set : 
```
scorex {
 logging {
    level = "DEBUG"
 }
```
in `ergo.conf` and it did not work, then I assembled jar with this in `application.conf` and it also did not work.

**Comment by ross-weir** [comment]
Very strange, I'll take a look

**Comment by ross-weir** [comment]
@pragmaxim I see why its not taking affect for lower logging levels (I only tested with `INFO` and above 😢 ) , I'll make another PR when I have time to fix

**Comment by greenhat** [comment]
It works in log file but not in stdout.

**Comment by pragmaxim** [comment]
@greenhat true, @ross-weir would you pls check it out?

**Comment by ross-weir** [comment]
> @greenhat true, @ross-weir would you pls check it out?

Apologies, haven't had time to work on ergo stuff

It looks like the issues been assigned/worked on

**Pull request merged**
