### PR TITLE
Clean sbt cache before assembly

### PR DESCRIPTION
**Pull request by andyceo**

### CODE REVIEW

**Comment by goral09** [comment]
Before calling `assembly` I would make double check that it's also `reload` and `update`.

**Comment by kushti** [comment]
@goral09 why these commands are needed?

**Comment by goral09** [comment]
@kushti it `reload`s the project definition in `build.sbt` and `update` s the dependencies.

**Comment by kushti** [comment]
@goral09 we're using sbt-lock plugin so dependency versions are locked.

**Comment by kushti** [comment]
@andyceo please add "reload"

**Comment by andyceo** [comment]
Done.

**Pull request merged**
