### PR TITLE
Dockerfile/Workflow: add support for aarch64

### PR DESCRIPTION
**Pull request by reqlez**
Similar to PR #1829 

- Changed to SBT version that has support for aarch64.

- Added port 9021 as it's being used in the new testnet.
 
- RE: openjdk docker image change: As per openjdk docker repo, starting with version 12, oraclelinux will be the default image. 
I'm using oracle image with version 11 here, because I found issues running this on RHEL-based systems with the other image.  Changed adduser command + jq/curl install commands since previous do not work with RHEL-based image.
 
- Added docker workflow to build/publish aarch64
 
- ( optional ) Changed min heap same as max for potential performance improvement as per:
https://blog.ycrash.io/2022/03/22/benefits-of-setting-initial-and-maximum-memory-size-to-the-same-value/

Inspiration for this PR:
ARM is a first-class citizen now, and provides increased performance for less cost at many datacentres, not to mention people can use this to run on Raspberry Pi / New Apple silicon systems.

### CODE REVIEW

**Comment by reqlez** [comment]
@kushti I had somebody also suggest trying out the eclipse-temurin:11-jre-jammy image versus going to openjdk's new Oracle choice. How do you feel about this? ( eclipse-temurin: https://developers.redhat.com/articles/2022/08/24/red-hat-expands-support-java-eclipse-temurin )

i'm testing that image on my Oracle Linux 8 / aarch64 environment to see if there are issues or not.

**Comment by reqlez** [comment]
I spoke to some community members, and they had concerns switching from a Debian-based OS image to RHEL-based.
I also feel better myself, using the eclipse-temurin:11-jre-jammy image as it is supported across many host OS versions, and working well in my tests with aarch64 on Oracle Linux as well.

**Review by wolf31o2 — APPROVED** [review]

**Comment by kushti** [comment]
@reqlez please open 9022 as well, as the new paiNet testnet is using it by default

**Comment by reqlez** [comment]
> @reqlez please open 9022 as well, as the new paiNet testnet is using it by default

Good for another re-run. Assuming node test failed due to port.

**Review by kushti — APPROVED** [review]

**Comment by kushti** [comment]
@reqlez approved, attached a bounty, please feel free to reach me over Discord or TG to get it

**Pull request merged**
