### PR TITLE
Fix BIP32 secret key derivation (child key < 32 bytes) in ergo-wallet

### LINKED ISSUE #1627: Incorrect BIP32 key derivation for some mnemonic phrases
### How to reproduce

Using `race relax argue hair sorry riot there spirit ready fetch food hedgehog hybrid mobile pretty` mnemonic and derive a secret key for `m/44'/429'/0'/0/0` path and then get the address(public key) from this derived secret key.
Expected (according to BIP32): 
`9eYMpbGgBf42bCcnB2nG3wQdqPzpCCw5eB1YaWUUen9uCaW3wwm` 
tested in Yoroi, Nautilus, SAFEW wallets, [bitcoinjs/bip32](https://github.com/bitcoinjs/bip32), sigma-rust
Got: 
`9ewv8sxJ1jfr6j3WUSbGPMTVx3TZgcJKdnjKCbJWhiJp5U62uhP` 
in Ergo node wallet, Ergo official mobile wallets

### Cause
For the above mnemonic hardened intermediate(`m/44'/429'`) child private key `childKey` BigInt value serializes to 31 bytes:

https://github.com/ergoplatform/ergo/blob/60bcda536bace5231ddc100e44097f059af80a72/ergo-wallet/src/main/scala/org/ergoplatform/wallet/secrets/ExtendedSecretKey.scala#L73

which is then used for the next path:
https://github.com/ergoplatform/ergo/blob/60bcda536bace5231ddc100e44097f059af80a72/ergo-wallet/src/main/scala/org/ergoplatform/wallet/secrets/ExtendedSecretKey.scala#L61

instead of required 32 bytes according to (BIP32)[https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#private-parent-key--private-child-key]. See `ser256(kpar)` used for hardened child key in the first bullet point:

> If so (hardened child): let I = HMAC-SHA512(Key = c<sub>par</sub>, Data = 0x00 || ser<sub>256</sub>(k<sub>par</sub>) || ser<sub>32</sub>(i)).

where `ser256` should be:

> ser<sub>256</sub>(p): serializes the integer p as a 32-byte sequence, most significant byte first.

### Fix
Use previous(incorrect) derivation for existing wallets (JSON key file loading), fixed key derivation for new wallets, and explicitly ask for key derivation type to be used for the wallets restored from mnemonic.

### What does it mean for your wallet?
Your mnemonic phrase will still produce the same wallet if restored in the same or compatible app (see "How to reproduce" section).
There is a chance that your mnemonic phrase will produce a different wallet if restored in another app and thus cannot be used to restore your wallet in a different app. See "How to reproduce" section for the list of compatible apps.

### PR DESCRIPTION
**Pull request by greenhat**
Ref #1627

This PR introduces the fix for incorrect BIP32 derivation in **ergo-wallet lib only** (child key less than 32 bytes, see #1627). #1841 is the PR enabling fixed derivation in the node's wallet. 

Corresponding PR in ergo-appkit that uses updated `ergo-wallet` - https://github.com/ergoplatform/ergo-appkit/pull/139

### Overview
**The ergo node's behavior is unchanged, i.e., it uses pre-1627 derivation in all cases (init, restore wallets).**
In ergo-wallet lib, use previous(incorrect) derivation when loading existing wallets (JSON key file loading) without `EncryptedSecret.usePre1627KeyDerivation` option set, fixed key derivation for new wallets and set `EncryptedSecret.usePre1627KeyDerivation`, and explicitly ask for key derivation type to be used for the wallets restored from mnemonic.

### Implementation details
The added `ExtendedSecretKey.usePre1627KeyDerivation` boolean option determines the behaviour of `ExtendedSecretKey.deriveChildSecretKey(...)` secret key derivation. It is set via `ExtendedSecretKey.deriveMasterKey(...)` which is a sort of a "constructor" method for `ExtendedSecretKey` class.
For user wallets stored in `JsonSecretStorage` a new `usePre1627KeyDerivation` argument added to `restore` and underlying `init` methods. It's effectively set to `false` for new wallets and expected to be set for restored wallets. The option is stored as `EncryptedSecret.usePre1627KeyDerivation` optional property, which is set to `true` on loading if it's not found in the JSON file, thus making existing wallets use previous(incorrect) key derivation.

#### ergo-wallet
- `ExtendedSecretKey.deriveMasterKey` has added `usePre1627KeyDerivation` parameter;
- `JsonSecretStorage.init` and `restore` has added `usePre1627KeyDerivation` parameter;
- ExtendedSecretKey serialization always uses fixed BIP32 derivation for the parsed key;

### CODE REVIEW

**Review by MrStahlfelge — APPROVED** [review]
Change works well for me with all mnemonics tested. (No code review)

**Review by aslesarenko — APPROVED** [review]

**Comment by aslesarenko** [comment]
@kushti this is probably important fix, please assign the milestone.

**Review by kushti — CHANGES_REQUESTED** [review]
How the implementation is tested? What are possible effects for node users, in regards with p2pk and mining script addresses?

**Comment by kushti** [comment]
> @kushti this is probably important fix, please assign the milestone.

How have you tested it?

**Comment by aslesarenko** [comment]
> @aslesarenko How have you tested it?

I'm not working on the issue, I just asked you to assign a milestone.

**Comment by kushti** [comment]
> > @aslesarenko How have you tested it?
> 
> @kushti I'm not working on the issue, I just asked you to assign a milestone.

@aslesarenko I need to understand how it is tested first

**Comment by greenhat** [comment]
> How the implementation is tested?

I wrote unit tests for `ExtendedSecretKey` with known test vectors for both derivations. 
For wallet loading, I wrote tests for `JsonSecretStorage` to test the old wallets are loaded with old derivation by default and new wallets are honoring an explicit flag usePre1627KeyDerivation`.Besides that, I set this flag to use fixed derivation in all tests that require this flag.

> What are possible effects for node users, in regards with p2pk and mining script addresses?

Existing wallets should be loaded with old derivation. New and restored wallets (`JsonSecretStorage.init` and `restore`) should explicitly specify what derivation should be used.
Regarding the mining script addresses, I did not test anything since I don't see how key derivation algo affects them.


I planned to look into splitting this PR into wallet lib PR and node PR as was discussed in #core recently.

**Comment by MrStahlfelge** [comment]
I have tested it in linked ergo-appkit build both manually and by unit tests, and used that build in ergoplatform/ergo-wallet-app#94 testing the derivations manually.

**Pull request merged**
